services:
  rust-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rust-backend
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=info
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "5173:5173"
    depends_on:
      - rust-backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge